class UserAlreadyExistsError(Exception):
    """ユーザーがすでに存在する場合のエラー"""
    pass
